apiVersion: v1
kind: Secret
metadata:
  name: url-monitor-secret
  labels:
    app: url-monitor
type: Opaque
data:
  # Base64 encoded Atlas connection string
  MONGO_URI: bW9uZ29kYitzcnY6Ly9rYXZpbnJhanNhcmF2YW5ha3VtYXJfZGJfdXNlcjpLYXZpbnJhaiU0MGF0bGFzQGNsdXN0ZXIwLmN6aTQyNnQubW9uZ29kYi5uZXQvdXJsbW9uaXRvcj9hcHBOYW1lPUNsdXN0ZXIw
