apiVersion: v1
kind: Secret
metadata:
  name: url-monitor-secret
  labels:
    app: url-monitor
type: Opaque
data:
  # Base64 encoded connection string: mongodb://mongo-service:27017/urlmonitor
  MONGO_URI: bW9uZ29kYjovL21vbmdvLXNlcnZpY2U6MjcwMTcvdXJsbW9uaXRvcg==
