apiVersion: v1
kind: Service
metadata:
  name: url-monitor-service
  labels:
    app: url-monitor
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
      name: http
  selector:
    app: url-monitor-app
